"""Component Adapter SDK for controlled detector extensions."""

from yolo_agent.components.adapters.base import (
    AdapterContext,
    AdapterValidationReport,
    ComponentAdapter,
    ExpectedArtifact,
    PatchOperation,
    PatchPreview,
    RollbackPlan,
    SmokeEvidenceKind,
    SmokeTestResult,
    WeightLoadResult,
)
from yolo_agent.components.adapters.dummy import DummyAdapter
from yolo_agent.components.adapters.registry import ComponentAdapterRegistry
from yolo_agent.components.adapters.runtime import AdapterRuntimePayload, RuntimePluginReference
from yolo_agent.components.adapters.runtime_contract import (
    AnnotationAdapter,
    AssignmentAdapter,
    AugmentationAdapter,
    CalibrationAdapter,
    DataPipelineAdapter,
    DistillationAdapter,
    GraphComponentAdapter,
    InferenceAdapter,
    LossAdapter,
    PostprocessAdapter,
    RuntimeAdapterContractError,
    RuntimeAdapterFacade,
    RuntimeAdapterMetadata,
    RuntimeAdapterProtocol,
    RuntimeCapability,
    SamplingAdapter,
    TrainingStrategyAdapter,
    adapt_component_adapter,
    assert_runtime_adapter,
    inspect_fake_implementation,
    validate_runtime_adapter,
)
from yolo_agent.components.adapters.neck import (
    GoldGatherDistributeAdapter,
    MultiScaleFusionAdapter,
    RTMDetLargeKernelNeckAdapter,
)

__all__ = [
    "AdapterContext",
    "AdapterValidationReport",
    "AdapterRuntimePayload",
    "ComponentAdapter",
    "ComponentAdapterRegistry",
    "DummyAdapter",
    "ExpectedArtifact",
    "PatchOperation",
    "PatchPreview",
    "RollbackPlan",
    "SmokeEvidenceKind",
    "RuntimePluginReference",
    "AnnotationAdapter",
    "AssignmentAdapter",
    "AugmentationAdapter",
    "CalibrationAdapter",
    "DataPipelineAdapter",
    "DistillationAdapter",
    "GraphComponentAdapter",
    "InferenceAdapter",
    "LossAdapter",
    "PostprocessAdapter",
    "RuntimeAdapterContractError",
    "RuntimeAdapterFacade",
    "RuntimeAdapterMetadata",
    "RuntimeAdapterProtocol",
    "RuntimeCapability",
    "SamplingAdapter",
    "TrainingStrategyAdapter",
    "adapt_component_adapter",
    "assert_runtime_adapter",
    "inspect_fake_implementation",
    "validate_runtime_adapter",
    "GoldGatherDistributeAdapter",
    "MultiScaleFusionAdapter",
    "RTMDetLargeKernelNeckAdapter",
    "SmokeTestResult",
    "WeightLoadResult",
]
