"""Teacher-student distillation primitives."""

from yolo_agent.components.distillation.losses import (
    DistillationWeights,
    YOLO26DistillationLoss,
    channel_agnostic_feature_loss,
    distillation_loss,
)
from yolo_agent.components.distillation.mechanisms import (
    DISTILLATION_COMPONENTS,
    DISTILLATION_MECHANISMS,
    DISTILLATION_ROUTE_IDS,
    DistillationMechanism,
    DistillationMechanismSpec,
)
from yolo_agent.components.distillation.mechanism_losses import (
    AttentionDistillationLoss,
    DistillationInputs,
    DistillationLossOutput,
    DistillationMechanismLoss,
    FeatureDistillationLoss,
    LocalizationDistillationLoss,
    LogitsDistillationLoss,
    MaskedFeatureDistillationLoss,
    QualityAwareDistillationLoss,
    RelationDistillationLoss,
    TeacherEnsembleDistillationLoss,
    SourceFreeTeacherDistillationLoss,
    CrossDomainTeacherDistillationLoss,
    ContrastiveDistillationLoss,
    build_distillation_mechanism_loss,
)
from yolo_agent.components.distillation.trainer import DistillationBatch, DistillationTrainerHook, MockDistillationTrainer
from yolo_agent.components.distillation.paper_mechanism_losses import (
    PAPER_MECHANISM_LOSSES,
    BaseNovelCommonalityDistillationLoss,
    BoVWConsistencyDistillationLoss,
    ClassifierResponseDistillationLoss,
    CrossScaleSelfDistillationLoss,
    EarlyLearningDistillationLoss,
    GLAMAttentionDistillationLoss,
    GlobalPrototypeDistillationLoss,
    HeteroAssistDistillationLoss,
    InstanceConditionalDistillationLoss,
    PearsonFeatureDistillationLoss,
    PredictionGuidedDistillationLoss,
    QueryDistillationLoss,
    RichnessMaskedDistillationLoss,
    StructuralSimilarityDistillationLoss,
)

__all__ = [
    "DistillationBatch",
    "DistillationTrainerHook",
    "DistillationWeights",
    "MockDistillationTrainer",
    "YOLO26DistillationLoss",
    "channel_agnostic_feature_loss",
    "distillation_loss",
    "DISTILLATION_COMPONENTS",
    "DISTILLATION_MECHANISMS",
    "DISTILLATION_ROUTE_IDS",
    "DistillationMechanism",
    "DistillationMechanismSpec",
    "DistillationInputs",
    "AttentionDistillationLoss",
    "DistillationLossOutput",
    "DistillationMechanismLoss",
    "FeatureDistillationLoss",
    "LocalizationDistillationLoss",
    "LogitsDistillationLoss",
    "MaskedFeatureDistillationLoss",
    "QualityAwareDistillationLoss",
    "RelationDistillationLoss",
    "TeacherEnsembleDistillationLoss",
    "SourceFreeTeacherDistillationLoss",
    "CrossDomainTeacherDistillationLoss",
    "ContrastiveDistillationLoss",
    "build_distillation_mechanism_loss",
    "PAPER_MECHANISM_LOSSES",
    "PearsonFeatureDistillationLoss",
    "RichnessMaskedDistillationLoss",
    "ClassifierResponseDistillationLoss",
    "InstanceConditionalDistillationLoss",
    "StructuralSimilarityDistillationLoss",
    "PredictionGuidedDistillationLoss",
    "HeteroAssistDistillationLoss",
    "GlobalPrototypeDistillationLoss",
    "BaseNovelCommonalityDistillationLoss",
    "BoVWConsistencyDistillationLoss",
    "GLAMAttentionDistillationLoss",
    "QueryDistillationLoss",
    "CrossScaleSelfDistillationLoss",
    "EarlyLearningDistillationLoss",
]
