"""Ultralytics YAML generator tests."""

from __future__ import annotations

from pathlib import Path

import yaml

from yolo_agent.adapters.ultralytics.yaml_generator import UltralyticsYamlGenerator
from yolo_agent.agents.candidate_generator import CandidateConfig


def _write_base_template(path: Path) -> None:
    path.write_text(
        "\n".join(
            [
                "nc: 80",
                "scales:",
                "  n: [0.50, 0.25, 1024]",
                "  s: [0.50, 0.50, 1024]",
                "backbone:",
                "  - [-1, 1, Conv, [64, 3, 2]]",
                "head:",
                "  - [-1, 1, Detect, [nc]]",
                "",
            ]
        ),
        encoding="utf-8",
    )


def test_baseline_yaml_generation_updates_safe_fields(tmp_path: Path) -> None:
    """Baseline generation should copy the template and safely update nc/scales."""
    template_path = tmp_path / "yolo11.yaml"
    output_dir = tmp_path / "generated_models"
    _write_base_template(template_path)
    candidate = CandidateConfig(
        candidate_id="yolo11n_baseline_n",
        base_model="yolo11n",
        scale="n",
        framework="ultralytics",
    )

    result = UltralyticsYamlGenerator().generate(candidate, template_path, output_dir, nc=3)

    assert result.output_path == output_dir / "yolo11n_baseline_n.yaml"
    generated = yaml.safe_load(result.output_path.read_text(encoding="utf-8"))
    assert generated["nc"] == 3
    assert generated["scales"] == {"n": [0.5, 0.25, 1024]}
    assert generated["backbone"]


def test_metadata_comment_is_written(tmp_path: Path) -> None:
    """Generated files should include traceable yolo-agent metadata comments."""
    template_path = tmp_path / "yolo11.yaml"
    _write_base_template(template_path)
    candidate = CandidateConfig(
        candidate_id="yolo11s_p2_head",
        base_model="yolo11s",
        scale="s",
        framework="ultralytics",
        components=["head.p2_small_object"],
        expected_effect=["Add high-resolution detection features."],
        risk="medium",
    )

    result = UltralyticsYamlGenerator().generate(candidate, template_path, tmp_path / "models", nc=1)
    text = result.output_path.read_text(encoding="utf-8")

    assert "# Generated by yolo-agent UltralyticsYamlGenerator." in text
    assert "# candidate_id: yolo11s_p2_head" in text
    assert "#   - head.p2_small_object" in text
    assert "TODO: head.p2_small_object requested" in text


def test_unsupported_component_warns_instead_of_crashing(tmp_path: Path) -> None:
    """Unsupported structural components should produce warnings and baseline YAML."""
    template_path = tmp_path / "yolo11.yaml"
    _write_base_template(template_path)
    candidate = CandidateConfig(
        candidate_id="yolo11n_custom",
        base_model="yolo11n",
        scale="n",
        framework="ultralytics",
        components=["backbone.unknown_block"],
    )

    result = UltralyticsYamlGenerator().generate(candidate, template_path, tmp_path / "models")

    assert result.output_path.exists()
    assert any("Unsupported structural component backbone.unknown_block" in warning for warning in result.warnings)


def test_dry_run_prints_changes_without_writing(tmp_path: Path, capsys) -> None:  # type: ignore[no-untyped-def]
    """Dry-run mode should describe changes without creating a file."""
    template_path = tmp_path / "yolo11.yaml"
    output_dir = tmp_path / "models"
    _write_base_template(template_path)
    candidate = CandidateConfig(
        candidate_id="yolo11s_fullpad",
        base_model="yolo11s",
        scale="s",
        framework="ultralytics",
        components=["neck.fullpad"],
    )

    result = UltralyticsYamlGenerator().generate(
        candidate,
        template_path,
        output_dir,
        nc=2,
        dry_run=True,
    )

    captured = capsys.readouterr().out
    assert result.dry_run is True
    assert not result.output_path.exists()
    assert "dry-run: would generate" in captured
    assert "Compatibility warning: neck.fullpad" in captured

