"""Ultralytics YAML generator tests."""

from __future__ import annotations

from pathlib import Path

import pytest
import yaml

from yolo_agent.adapters.ultralytics.yaml_generator import (
    UnsupportedYamlComponentError,
    UltralyticsYamlGenerator,
)
from yolo_agent.agents.candidate_generator import CandidateConfig


def _write_base_template(path: Path) -> None:
    path.write_text(
        "\n".join(
            [
                "nc: 80",
                "scales:",
                "  n: [0.50, 0.25, 1024]",
                "  s: [0.50, 0.50, 1024]",
                "backbone:",
                "  - [-1, 1, Conv, [64, 3, 2]]",
                "head:",
                "  - [-1, 1, Detect, [nc]]",
                "",
            ]
        ),
        encoding="utf-8",
    )


def test_baseline_yaml_generation_updates_safe_fields(tmp_path: Path) -> None:
    """Baseline generation should copy the template and safely update nc/scales."""
    template_path = tmp_path / "yolo11.yaml"
    output_dir = tmp_path / "generated_models"
    _write_base_template(template_path)
    candidate = CandidateConfig(
        candidate_id="yolo11n_baseline_n",
        base_model="yolo11n",
        scale="n",
        framework="ultralytics",
    )

    result = UltralyticsYamlGenerator().generate(candidate, template_path, output_dir, nc=3)

    assert result.output_path == output_dir / "yolo11n_baseline_n.yaml"
    generated = yaml.safe_load(result.output_path.read_text(encoding="utf-8"))
    assert generated["nc"] == 3
    assert generated["scales"] == {"n": [0.5, 0.25, 1024]}
    assert generated["backbone"]


def test_metadata_comment_is_written_for_baseline(tmp_path: Path) -> None:
    """Generated files should include traceable yolo-agent metadata comments."""
    template_path = tmp_path / "yolo11.yaml"
    _write_base_template(template_path)
    candidate = CandidateConfig(
        candidate_id="yolo11s_p2_head",
        base_model="yolo11s",
        scale="s",
        framework="ultralytics",
        expected_effect=["Add high-resolution detection features."],
        risk="medium",
    )

    result = UltralyticsYamlGenerator().generate(candidate, template_path, tmp_path / "models", nc=1)
    text = result.output_path.read_text(encoding="utf-8")

    assert "# Generated by yolo-agent UltralyticsYamlGenerator." in text
    assert "# candidate_id: yolo11s_p2_head" in text
    assert "# expected_effect:" in text


@pytest.mark.parametrize("component_id", ["head.p2_small_object", "backbone.unknown_block"])
def test_structural_components_fail_closed(
    tmp_path: Path,
    component_id: str,
) -> None:
    template_path = tmp_path / "yolo11.yaml"
    _write_base_template(template_path)
    candidate = CandidateConfig(
        candidate_id="yolo11n_custom",
        base_model="yolo11n",
        scale="n",
        framework="ultralytics",
        components=[component_id],
    )

    with pytest.raises(UnsupportedYamlComponentError, match="ComponentExecutionBridge"):
        UltralyticsYamlGenerator().generate(candidate, template_path, tmp_path / "models")
    assert not (tmp_path / "models" / "yolo11n_custom.yaml").exists()


def test_dry_run_prints_changes_without_writing(tmp_path: Path, capsys) -> None:  # type: ignore[no-untyped-def]
    """Dry-run mode should describe changes without creating a file."""
    template_path = tmp_path / "yolo11.yaml"
    output_dir = tmp_path / "models"
    _write_base_template(template_path)
    candidate = CandidateConfig(
        candidate_id="yolo11s_fullpad",
        base_model="yolo11s",
        scale="s",
        framework="ultralytics",
    )

    result = UltralyticsYamlGenerator().generate(
        candidate,
        template_path,
        output_dir,
        nc=2,
        dry_run=True,
    )

    captured = capsys.readouterr().out
    assert result.dry_run is True
    assert not result.output_path.exists()
    assert "dry-run: would generate" in captured
    assert "change: set nc=2" in captured
