"""Generate README status sections from machine-readable artifacts.

The generator replaces the three hand-maintained status blocks in both READMEs
(implementation readiness, training readiness, reproduction evidence) and writes
the combined report to ``docs/generated/current-status.md`` and
``docs/generated/current-status.zh-CN.md``. Run with ``--check`` (used by the
docs consistency tests) to verify that the committed files are current.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any, Sequence

import yaml

STATUS_START = "<!-- BEGIN GENERATED STATUS -->"
STATUS_END = "<!-- END GENERATED STATUS -->"

COVERAGE_REPORT = Path("docs/paper-adapter-coverage.yaml")
ACCEPTANCE_REPORT = Path("docs/paper-coverage-acceptance.yaml")
CAMPAIGN_MANIFEST = Path("configs/research/paper_83_manifest.yaml")
PRETRAINING_ACCEPTANCE = Path("artifacts/pretraining_acceptance.yaml")
RUNTIME_PREFLIGHT = Path("artifacts/paper_83_runtime_preflight.yaml")
TRAINING_RELEASE = Path("artifacts/training_release_v1.yaml")
MATURITY_REGISTRY = Path("runs/component_maturity_registry.yaml")

GENERATED_EN = Path("docs/generated/current-status.md")
GENERATED_ZH = Path("docs/generated/current-status.zh-CN.md")
README_PATHS = (Path("README.md"), Path("README.zh-CN.md"))

GENERATED_HEADER = (
    "<!-- AUTO-GENERATED by `python -m yolo_agent.tools.docs_status`."
    " Do not edit by hand; rerun the tool instead. -->"
)


def _load_yaml(path: Path, root: Path) -> dict[str, Any] | None:
    full = root / path
    if not full.is_file():
        return None
    return yaml.safe_load(full.read_text(encoding="utf-8")) or {}


def _short_date(value: Any) -> str:
    return str(value)[:10] if value else "unknown date"


def _ratio(numerator: Any, denominator: Any) -> str:
    try:
        ratio = float(numerator) / float(denominator) * 100.0
    except (TypeError, ZeroDivisionError):
        return f"{numerator}/{denominator}"
    return f"{numerator}/{denominator} ({ratio:.1f}%)"


def _target(value: Any) -> str:
    try:
        return f">={float(value) * 100:.0f}%"
    except (TypeError, ValueError):
        return "-"


def collect_status(root: Path | str = ".") -> dict[str, Any]:
    """Read every machine-readable status source. Missing files degrade to None."""
    base = Path(root)
    coverage = _load_yaml(COVERAGE_REPORT, base)
    acceptance = _load_yaml(ACCEPTANCE_REPORT, base)
    manifest = _load_yaml(CAMPAIGN_MANIFEST, base)
    pretraining = _load_yaml(PRETRAINING_ACCEPTANCE, base)
    preflight = _load_yaml(RUNTIME_PREFLIGHT, base)
    release = _load_yaml(TRAINING_RELEASE, base)
    registry = _load_yaml(MATURITY_REGISTRY, base)

    campaign = (pretraining or {}).get("paper_campaign") or {}

    metrics: list[dict[str, Any]] = []
    for metric_id, item in sorted(((acceptance or {}).get("metrics") or {}).items()):
        metrics.append(
            {
                "id": metric_id,
                "result": _ratio(item.get("numerator"), item.get("denominator")),
                "target": _target(item.get("target")),
                "passed": bool(item.get("passed")),
            }
        )

    maturity_counts = (coverage or {}).get("maturity_counts") or {}
    registry_summary: dict[str, Any] | None = None
    if registry and isinstance(registry.get("overlays"), list):
        overlays = registry["overlays"]
        statuses: dict[str, int] = {}
        components: set[str] = set()
        for overlay in overlays:
            components.add(str(overlay.get("component_id")))
            for artifact in overlay.get("artifacts") or []:
                key = str(artifact.get("status"))
                statuses[key] = statuses.get(key, 0) + 1
        registry_summary = {
            "overlay_count": len(overlays),
            "distinct_components": len(components),
            "artifacts_passed": statuses.get("passed", 0),
            "artifacts_failed": statuses.get("failed", 0),
        }

    return {
        "coverage": {
            "paper_count": (coverage or {}).get("paper_count"),
            "implemented": (coverage or {}).get("implemented_component_id_count"),
            "adapter_classes": (coverage or {}).get("unique_adapter_class_count"),
            "pilot_reproduced": (coverage or {}).get("pilot_reproduced_count"),
            "audited_at": _short_date((coverage or {}).get("audited_at")),
            "snapshot_hash": (coverage or {}).get("snapshot_hash"),
        },
        "acceptance": {
            "rows": metrics,
            "report_hash": (acceptance or {}).get("report_hash"),
            "status": (acceptance or {}).get("status"),
            "exact_reproduction": len(
                (acceptance or {}).get("exact_reproduction_paper_ids") or []
            ),
            "separate_detector_family": len(
                (acceptance or {}).get("separate_detector_family_paper_ids") or []
            ),
            "insufficient_information": len(
                (acceptance or {}).get("insufficient_information_paper_ids") or []
            ),
        },
        "campaign": {
            "manifest_paper_count": campaign.get(
                "manifest_paper_count", (manifest or {}).get("paper_count")
            ),
            "spec_complete": campaign.get("spec_complete"),
            "code_bound": campaign.get("code_bound"),
            "runtime_integrated": campaign.get("runtime_integrated"),
            "unit_tested": campaign.get("unit_tested"),
            "non_mock_smoke_passed": campaign.get("non_mock_smoke_passed"),
            "compatibility_validated": campaign.get("compatibility_validated"),
            "implementation_ready": campaign.get("implementation_ready"),
            "blocked": campaign.get("blocked"),
            "evaluated_at": _short_date((pretraining or {}).get("evaluated_at")),
        },
        "readiness": {
            "preflight_paper_count": (preflight or {}).get("paper_count"),
            "preflight_passed": (preflight or {}).get("passed"),
            "preflight_failed": (preflight or {}).get("failed"),
            "unknown_runtime_hooks": (preflight or {}).get("unknown_runtime_hooks"),
            "acceptance_verdict": (pretraining or {}).get("verdict"),
            "release_status": (release or {}).get("release_status"),
            "release_commit": str((release or {}).get("git_commit") or "")[:8],
            "release_created_at": _short_date((release or {}).get("created_at")),
            "real_training_executed": bool(
                (release or {}).get("real_training_executed")
            ),
        },
        "reproduction": {
            "pilot_reproduced": (coverage or {}).get("pilot_reproduced_count"),
            "full_reproduced": maturity_counts.get("full_reproduced"),
            "confirmed_multi_seed": maturity_counts.get("confirmed_multi_seed"),
        },
        "registry": registry_summary,
    }


def _table(headers: list[str], rows: list[list[str]]) -> list[str]:
    lines = ["| " + " | ".join(headers) + " |", "| " + " | ".join(["---"] * len(headers)) + " |"]
    lines.extend("| " + " | ".join(row) + " |" for row in rows)
    return lines


def render_status_en(status: dict[str, Any], *, full_report: bool = False) -> str:
    """Render the English status blocks."""
    campaign = status["campaign"]
    readiness = status["readiness"]
    reproduction = status["reproduction"]
    acceptance = status["acceptance"]
    registry = status["registry"] or {}
    lines: list[str] = []

    if full_report:
        coverage = status["coverage"]
        lines.append("### Research coverage")
        lines.append("")
        lines.extend(
            _table(
                ["Frozen paper records", "Implemented component IDs", "Unique Python adapter classes", "Pilot reproduced components"],
                [[
                    str(coverage["paper_count"]),
                    str(coverage["implemented"]),
                    str(coverage["adapter_classes"]),
                    str(coverage["pilot_reproduced"]),
                ]],
            )
        )
        lines.append("")
        lines.append(
            f"Audit snapshot: `{coverage['snapshot_hash']}` (audited {coverage['audited_at']})."
        )
        lines.append("")
        lines.append("### Coverage acceptance")
        lines.append("")
        lines.extend(
            _table(
                ["Metric", "Result", "Target", "Passed"],
                [[row["id"], row["result"], row["target"], str(row["passed"]).lower()] for row in acceptance["rows"]],
            )
        )
        lines.append("")
        lines.append(
            f"Catalog-wide certified-adapter mapping is reported in the metric rows above; "
            f"this is reusable component adaptation, not exact paper reproduction. "
            f"Exact reproduction: {acceptance['exact_reproduction']}; "
            f"separate detector family: {acceptance['separate_detector_family']}; "
            f"insufficient information: {acceptance['insufficient_information']}. "
            f"Acceptance status: `{acceptance['status']}`; "
            f"acceptance hash: `{acceptance['report_hash']}`."
        )
        lines.append("")

    lines.append("### Implementation readiness (Paper-83 campaign)")
    lines.append("")
    lines.append(
        f"Source: `{PRETRAINING_ACCEPTANCE.as_posix()}` (evaluated {campaign['evaluated_at']}); "
        f"manifest: `{CAMPAIGN_MANIFEST.as_posix()}`."
    )
    lines.append("")
    gate_rows = [
        ("Papers in campaign manifest", campaign["manifest_paper_count"]),
        ("Specification complete", campaign["spec_complete"]),
        ("Code-bound implementation", campaign["code_bound"]),
        ("Runtime integrated", campaign["runtime_integrated"]),
        ("Unit tested", campaign["unit_tested"]),
        ("Non-mock smoke passed", campaign["non_mock_smoke_passed"]),
        ("Compatibility validated", campaign["compatibility_validated"]),
        ("Implementation ready", campaign["implementation_ready"]),
        ("Blocked", campaign["blocked"]),
    ]
    lines.extend(_table(["Gate", "Result"], [[name, str(value)] for name, value in gate_rows]))
    lines.append("")

    lines.append("### Training readiness")
    lines.append("")
    lines.append(
        f"Sources: `{RUNTIME_PREFLIGHT.as_posix()}`, `{PRETRAINING_ACCEPTANCE.as_posix()}` "
        f"(evaluated {campaign['evaluated_at']}), `{TRAINING_RELEASE.as_posix()}` "
        f"(created {readiness['release_created_at']})."
    )
    lines.append("")
    lines.extend(
        _table(
            ["Gate", "Result"],
            [
                [
                    "Runtime preflight",
                    f"{readiness['preflight_passed']}/{readiness['preflight_paper_count']} passed; "
                    f"failed: {readiness['preflight_failed']}; "
                    f"unknown runtime hooks: {readiness['unknown_runtime_hooks']}",
                ],
                ["Pretraining acceptance", f"`{readiness['acceptance_verdict']}`"],
                [
                    "Training release",
                    f"`{readiness['release_status']}`, frozen at git commit `{readiness['release_commit']}`",
                ],
            ],
        )
    )
    lines.append("")
    lines.append(
        "`real_training_executed` is `false` in every artifact: these gates certify "
        "readiness, not training results."
    )
    lines.append("")

    lines.append("### Reproduction evidence")
    lines.append("")
    lines.append(
        f"Sources: `{COVERAGE_REPORT.as_posix()}` (`pilot_reproduced_count`, "
        f"`maturity_counts`), `{ACCEPTANCE_REPORT.as_posix()}` "
        f"(`exact_reproduction_paper_ids`)."
    )
    lines.append("")
    lines.extend(
        _table(
            ["Evidence level", "Count"],
            [
                ["Pilot reproduced components", str(reproduction["pilot_reproduced"])],
                ["Exact paper reproduction (full)", str(reproduction["full_reproduced"])],
                ["Multi-seed confirmed", str(reproduction["confirmed_multi_seed"])],
            ],
        )
    )
    lines.append("")
    lines.append(
        "Implemented is not reproduced. A single pilot improvement is `possible`, "
        "not `confirmed`; paper metrics never count as promotion evidence."
    )

    if full_report:
        lines.append("")
        lines.append("### Component maturity registry")
        lines.append("")
        if registry:
            lines.extend(
                _table(
                    ["Overlays", "Distinct components", "Artifacts passed", "Artifacts failed"],
                    [[
                        str(registry["overlay_count"]),
                        str(registry["distinct_components"]),
                        str(registry["artifacts_passed"]),
                        str(registry["artifacts_failed"]),
                    ]],
                )
            )
            lines.append("")
            lines.append(
                f"Source: `{MATURITY_REGISTRY.as_posix()}`. Overlay evidence covers "
                "runtime payloads, unit-test reports, and smoke reports per component."
            )
        else:
            lines.append(
                f"`{MATURITY_REGISTRY.as_posix()}` is not present in this checkout; "
                "registry-derived counts are omitted."
            )
    return "\n".join(lines)


def render_status_zh(status: dict[str, Any], *, full_report: bool = False) -> str:
    """Render the Chinese status blocks (same structured source as English)."""
    campaign = status["campaign"]
    readiness = status["readiness"]
    reproduction = status["reproduction"]
    lines: list[str] = []

    lines.append("### 实现就绪（Paper-83 战役）")
    lines.append("")
    lines.append(
        f"来源：`{PRETRAINING_ACCEPTANCE.as_posix()}`（评估于 {campaign['evaluated_at']}）；"
        f"manifest：`{CAMPAIGN_MANIFEST.as_posix()}`。"
    )
    lines.append("")
    gate_rows = [
        ("战役 manifest 中的论文数", campaign["manifest_paper_count"]),
        ("规格完整", campaign["spec_complete"]),
        ("代码绑定实现", campaign["code_bound"]),
        ("运行时集成", campaign["runtime_integrated"]),
        ("单元测试", campaign["unit_tested"]),
        ("非 mock smoke 通过", campaign["non_mock_smoke_passed"]),
        ("兼容性验证", campaign["compatibility_validated"]),
        ("实现就绪", campaign["implementation_ready"]),
        ("阻塞", campaign["blocked"]),
    ]
    lines.extend(_table(["关卡", "结果"], [[name, str(value)] for name, value in gate_rows]))
    lines.append("")

    lines.append("### 训练就绪")
    lines.append("")
    lines.append(
        f"来源：`{RUNTIME_PREFLIGHT.as_posix()}`、`{PRETRAINING_ACCEPTANCE.as_posix()}`"
        f"（评估于 {campaign['evaluated_at']}）、`{TRAINING_RELEASE.as_posix()}`"
        f"（创建于 {readiness['release_created_at']}）。"
    )
    lines.append("")
    lines.extend(
        _table(
            ["关卡", "结果"],
            [
                [
                    "运行时 preflight",
                    f"{readiness['preflight_passed']}/{readiness['preflight_paper_count']} 通过；"
                    f"失败：{readiness['preflight_failed']}；"
                    f"未知 runtime hooks：{readiness['unknown_runtime_hooks']}",
                ],
                ["预训练验收", f"`{readiness['acceptance_verdict']}`"],
                [
                    "训练发布",
                    f"`{readiness['release_status']}`，冻结于 git commit `{readiness['release_commit']}`",
                ],
            ],
        )
    )
    lines.append("")
    lines.append(
        "所有 artifact 中 `real_training_executed` 均为 `false`：这些关卡证明的是"
        "就绪状态，不是训练结果。"
    )
    lines.append("")

    lines.append("### 复现证据")
    lines.append("")
    lines.append(
        f"来源：`{COVERAGE_REPORT.as_posix()}`（`pilot_reproduced_count`、"
        f"`maturity_counts`）、`{ACCEPTANCE_REPORT.as_posix()}`"
        f"（`exact_reproduction_paper_ids`）。"
    )
    lines.append("")
    lines.extend(
        _table(
            ["证据层级", "数量"],
            [
                ["Pilot 复现组件", str(reproduction["pilot_reproduced"])],
                ["论文精确复现（full）", str(reproduction["full_reproduced"])],
                ["多 seed 确认", str(reproduction["confirmed_multi_seed"])],
            ],
        )
    )
    lines.append("")
    lines.append(
        "实现不等于复现。单次 pilot 改善只是 `possible`，不是 `confirmed`；"
        "论文指标永远不算晋升证据。"
    )
    return "\n".join(lines)


def render_full_report_en(status: dict[str, Any]) -> str:
    body = render_status_en(status, full_report=True)
    return GENERATED_HEADER + "\n\n# Current Status\n\n" + body + "\n"


def render_full_report_zh(status: dict[str, Any]) -> str:
    body = render_status_zh(status, full_report=True)
    return GENERATED_HEADER + "\n\n# 当前状态\n\n" + body + "\n"


def _replace_block(text: str, start: str, end: str, replacement: str) -> str:
    """Replace the content between markers; raise if markers are missing."""
    start_index = text.find(start)
    end_index = text.find(end)
    if start_index == -1 or end_index == -1 or end_index < start_index:
        raise ValueError(f"marker block not found: {start}")
    head = text[: start_index + len(start)]
    tail = text[end_index:]
    return head + "\n" + replacement + "\n" + tail


def _update_readme(path: Path, content: str, *, encoding: str) -> bool:
    current = path.read_text(encoding=encoding)
    updated = _replace_block(current, STATUS_START, STATUS_END, content)
    if updated == current:
        return False
    path.write_text(updated, encoding=encoding)
    return True


def generate(root: Path | str = ".", *, check: bool = False) -> bool:
    """Write (or, with check=True, verify) every generated status target."""
    base = Path(root)
    status = collect_status(base)
    en_block = render_status_en(status)
    zh_block = render_status_zh(status)
    en_report = render_full_report_en(status)
    zh_report = render_full_report_zh(status)

    readme_blocks = {
        base / README_PATHS[0]: en_block,
        base / README_PATHS[1]: zh_block,
    }
    reports = {
        base / GENERATED_EN: (en_report, "utf-8"),
        base / GENERATED_ZH: (zh_report, "utf-8-sig"),
    }

    if check:
        stale: list[Path] = []
        for path, content in readme_blocks.items():
            current = path.read_text(encoding="utf-8-sig") if path.is_file() else ""
            try:
                updated = _replace_block(current, STATUS_START, STATUS_END, content)
            except ValueError:
                stale.append(path)
                continue
            if updated != current:
                stale.append(path)
        for path, (content, encoding) in reports.items():
            current = path.read_text(encoding=encoding) if path.is_file() else ""
            if current != content:
                stale.append(path)
        return not stale

    for path, content in readme_blocks.items():
        _update_readme(path, content, encoding="utf-8-sig")
    for path, (content, encoding) in reports.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding=encoding)
    return True


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="python -m yolo_agent.tools.docs_status",
        description="Generate README status blocks and docs/generated/current-status reports.",
    )
    parser.add_argument("--root", type=Path, default=Path("."), help="Repository root.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify committed files are current instead of writing; exits 1 when stale.",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    if args.check:
        current = generate(args.root, check=True)
        print("documentation status is current" if current else "generated status is stale")
        return 0 if current else 1
    generate(args.root)
    print("documentation status regenerated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
