"""Core domain models and orchestration primitives."""

from yolo_agent.core.artifact_manifest import (
    ARTIFACT_MANIFEST_SCHEMA_VERSION,
    ArtifactManifest,
    ArtifactManifestEntry,
    ArtifactType,
    sha256_directory,
    sha256_file,
)
from yolo_agent.core.schemas import AgentConfig, DatasetProfile, DeploymentConstraints
from yolo_agent.core.task_spec import (
    DatasetSpec,
    DeploymentSpec,
    MetricPriority,
    ScenarioHint,
    TaskSpec,
)
from yolo_agent.core.evidence_store import EvidenceStore
from yolo_agent.core.event_log import EventLog, EventLogEntry
from yolo_agent.core.executor import (
    BenchmarkImporter,
    BenchmarkImportResult,
    DryRunExecutor,
    ExecutionResult,
    ExecutionStatus,
    ExperimentExecutor,
    ShellExecutor,
    UltralyticsExecutor,
    UltralyticsTrainExecutor,
    coerce_metric_value,
    read_metric_mapping,
    read_metric_records,
)
from yolo_agent.core.command_spec import CommandSpec, CommandType
from yolo_agent.core.execution_queue import (
    ExecutionQueue,
    ExecutionQueueItem,
    ExecutionQueueStore,
    QueueStatus,
    queue_status_from_execution_status,
)
from yolo_agent.core.evidence_contract import (
    EvidenceContract,
    EvidenceGate,
    EvidenceGateResult,
    EvidenceRequirement,
    EvidenceStatus,
    NO_EVIDENCE_WARNING,
)
from yolo_agent.core.evidence_index import EvidenceIndex, MetricEvidenceQuery, SelectionMode
from yolo_agent.core.experiment_graph import (
    Evidence,
    ExperimentNode,
    ExperimentPlan,
    ExperimentStatus,
    METRIC_SCHEMA_VERSION,
    MetricEvidence,
    MetricValue,
)
from yolo_agent.core.label_quality import (
    AnnotationRules,
    LabelQualityIssue,
    LabelQualityReport,
    PredictionBox,
    YoloBox,
    analyze_label_quality,
)
from yolo_agent.core.dataset_versioning import (
    DatasetDiff,
    DatasetFileRecord,
    DatasetVersionManifest,
    DatasetVersionStore,
)
from yolo_agent.core.dataset_promotion import (
    DatasetPromotionPolicy,
    DatasetPromotionPolicyConfig,
    DatasetPromotionResult,
    PromotionDecision,
    ReviewedLabelSample,
    ReviewedLabels,
    ReviewStatus,
    load_reviewed_labels,
)
from yolo_agent.core.decision_ledger import (
    DECISION_LEDGER_SCHEMA_VERSION,
    DecisionLedger,
    DecisionLedgerRecord,
    DecisionReplaySnapshot,
    build_replay_snapshot,
    sha256_model,
    sha256_path,
)
from yolo_agent.core.dataset_split import (
    DatasetSample,
    DatasetSplitPlan,
    DatasetSplitPlanner,
    DuplicateGroup,
    LeakagePair,
    SplitAssignment,
)
from yolo_agent.core.loop_state import KNOWN_LOOP_STAGES, LoopStageState, LoopState
from yolo_agent.core.run_context import RunContext
from yolo_agent.core.run_lineage import (
    LINEAGE_SCHEMA_VERSION,
    RunLineageGraph,
    RunLineageRecord,
    RunLineageStore,
    build_lineage_record,
)
from yolo_agent.core.stage_contract import (
    ArtifactContract,
    LoopStageContracts,
    RetryPolicy,
    StageContract,
    StageContractCheck,
)

__all__ = [
    "AgentConfig",
    "ARTIFACT_MANIFEST_SCHEMA_VERSION",
    "ArtifactManifest",
    "ArtifactManifestEntry",
    "ArtifactType",
    "BenchmarkImporter",
    "BenchmarkImportResult",
    "CommandSpec",
    "CommandType",
    "DatasetProfile",
    "DatasetDiff",
    "DatasetFileRecord",
    "DatasetPromotionPolicy",
    "DatasetPromotionPolicyConfig",
    "DatasetPromotionResult",
    "DatasetSample",
    "DatasetSplitPlan",
    "DatasetSplitPlanner",
    "DeploymentConstraints",
    "DatasetSpec",
    "DatasetVersionManifest",
    "DatasetVersionStore",
    "DecisionLedger",
    "DecisionLedgerRecord",
    "DecisionReplaySnapshot",
    "DECISION_LEDGER_SCHEMA_VERSION",
    "KNOWN_LOOP_STAGES",
    "DeploymentSpec",
    "DuplicateGroup",
    "DryRunExecutor",
    "Evidence",
    "EvidenceContract",
    "EventLog",
    "EventLogEntry",
    "EvidenceGate",
    "EvidenceGateResult",
    "EvidenceIndex",
    "EvidenceRequirement",
    "EvidenceStore",
    "EvidenceStatus",
    "ExecutionResult",
    "ExecutionStatus",
    "ExecutionQueue",
    "ExecutionQueueItem",
    "ExecutionQueueStore",
    "ExperimentExecutor",
    "ExperimentNode",
    "ExperimentPlan",
    "ExperimentStatus",
    "AnnotationRules",
    "ArtifactContract",
    "LabelQualityIssue",
    "LabelQualityReport",
    "LeakagePair",
    "LINEAGE_SCHEMA_VERSION",
    "LoopStageState",
    "LoopStageContracts",
    "LoopState",
    "MetricPriority",
    "METRIC_SCHEMA_VERSION",
    "MetricEvidence",
    "MetricEvidenceQuery",
    "MetricValue",
    "NO_EVIDENCE_WARNING",
    "PredictionBox",
    "QueueStatus",
    "PromotionDecision",
    "RunContext",
    "RunLineageGraph",
    "RunLineageRecord",
    "RunLineageStore",
    "RetryPolicy",
    "ReviewedLabelSample",
    "ReviewedLabels",
    "ReviewStatus",
    "ScenarioHint",
    "SelectionMode",
    "ShellExecutor",
    "SplitAssignment",
    "StageContract",
    "StageContractCheck",
    "TaskSpec",
    "UltralyticsExecutor",
    "UltralyticsTrainExecutor",
    "YoloBox",
    "analyze_label_quality",
    "build_lineage_record",
    "build_replay_snapshot",
    "coerce_metric_value",
    "read_metric_mapping",
    "read_metric_records",
    "load_reviewed_labels",
    "queue_status_from_execution_status",
    "sha256_directory",
    "sha256_file",
    "sha256_model",
    "sha256_path",
]
