"""Core domain models and orchestration primitives."""

from yolo_agent.core.artifact_manifest import (
    ARTIFACT_MANIFEST_SCHEMA_VERSION,
    ArtifactManifest,
    ArtifactManifestEntry,
    ArtifactType,
    sha256_directory,
    sha256_file,
)
from yolo_agent.core.schemas import AgentConfig, DatasetProfile, DeploymentConstraints
from yolo_agent.core.task_spec import (
    DatasetSpec,
    DeploymentSpec,
    MetricPriority,
    ScenarioHint,
    TaskSpec,
)
from yolo_agent.core.evidence_store import EvidenceStore
from yolo_agent.core.coco_baseline_evidence import (
    COCO_BASELINE_REQUIRED_ARTIFACTS,
    COCO_BASELINE_REQUIRED_METRICS,
    CocoBaselineEvidenceContract,
    CocoBaselineEvidenceResult,
    CocoBaselineNodeStatus,
    coco_metric_aliases,
)
from yolo_agent.core.coco_error_selection import (
    CocoErrorFactSelector,
    CocoErrorFocus,
    CocoErrorSelectionResult,
    select_coco_error_facts,
)
from yolo_agent.core.event_log import EventLog, EventLogEntry
from yolo_agent.core.executor import (
    BenchmarkImporter,
    BenchmarkImportResult,
    DryRunExecutor,
    ExecutionResult,
    ExecutionStatus,
    ExperimentExecutor,
    ShellExecutor,
    UltralyticsExecutor,
    UltralyticsTrainExecutor,
    coerce_metric_value,
    read_metric_mapping,
    read_metric_records,
)
from yolo_agent.core.command_spec import CommandSpec, CommandType, ResourceRequirements
from yolo_agent.core.execution_queue import (
    ExecutionQueue,
    ExecutionQueueItem,
    ExecutionQueueStore,
    QueueStatus,
    queue_status_from_execution_status,
)
from yolo_agent.core.round_execution_plan import (
    ROUND_EXECUTION_PLAN_SCHEMA_VERSION,
    RoundAblationNode,
    RoundAssignment,
    RoundExecutionPlan,
    RoundStageSpec,
    SurvivorDecision,
    build_round_execution_plan,
)
from yolo_agent.core.evidence_contract import (
    EvidenceContract,
    EvidenceGate,
    EvidenceGateResult,
    EvidenceRequirement,
    EvidenceStatus,
    NO_EVIDENCE_WARNING,
)
from yolo_agent.core.evidence_index import EvidenceIndex, MetricEvidenceQuery, SelectionMode
from yolo_agent.core.evidence_selector import EvidenceSelection, EvidenceSelector, select_metric_evidence
from yolo_agent.core.matched_baseline import (
    MATCHED_BASELINE_SCHEMA_VERSION,
    MatchedBaselineControl,
    MatchedBaselineKey,
    PairedMetricDelta,
    build_match_key,
    match_baseline_control,
    paired_metric_delta,
)
from yolo_agent.core.paired_experiment import (
    PairedBootstrapCI,
    PairedErrorFactDelta,
    PairedExperimentResult,
    build_paired_experiment_result,
)
from yolo_agent.core.policy_variables import PolicyVariableClassification, classify_policy_variables
from yolo_agent.core.error_facts import (
    ErrorFact,
    ErrorFactIndex,
    ErrorFactQuery,
    ErrorFactStore,
    ErrorFactType,
    build_error_facts_from_coco_error_report,
    build_error_facts_from_coco_metrics,
)
from yolo_agent.core.experiment_graph import (
    Evidence,
    ExperimentNode,
    ExperimentPlan,
    ExperimentStatus,
    METRIC_SCHEMA_VERSION,
    MetricEvidence,
    MetricValue,
)
from yolo_agent.core.label_quality import (
    AnnotationRules,
    LabelQualityIssue,
    LabelQualityReport,
    PredictionBox,
    YoloBox,
    analyze_label_quality,
)
from yolo_agent.core.llm_config import LLMDecisionConfig, PromptContract, load_llm_decision_config
from yolo_agent.core.dataset_versioning import (
    DatasetDiff,
    DatasetFileRecord,
    DatasetVersionManifest,
    DatasetVersionStore,
)
from yolo_agent.core.dataset_promotion import (
    DatasetPromotionPolicy,
    DatasetPromotionPolicyConfig,
    DatasetPromotionResult,
    PromotionDecision,
    ReviewedLabelSample,
    ReviewedLabels,
    ReviewStatus,
    load_reviewed_labels,
)
from yolo_agent.core.decision_ledger import (
    DECISION_LEDGER_SCHEMA_VERSION,
    DecisionLedger,
    DecisionLedgerRecord,
    DecisionReplaySnapshot,
    build_replay_snapshot,
    sha256_model,
    sha256_path,
)
from yolo_agent.core.dataset_split import (
    DatasetSample,
    DatasetSplitPlan,
    DatasetSplitPlanner,
    DuplicateGroup,
    LeakagePair,
    SplitAssignment,
)
from yolo_agent.core.loop_state import KNOWN_LOOP_STAGES, LoopStageState, LoopState
from yolo_agent.core.loop_status import (
    AutoOptimizationStatus,
    EvidenceStatusSummary,
    LoopRunStatus,
    QueueItemStatus,
    TrainingHeartbeat,
    load_loop_status,
    render_loop_status,
)
from yolo_agent.core.run_context import RunContext
from yolo_agent.core.run_lineage import (
    LINEAGE_SCHEMA_VERSION,
    RunLineageGraph,
    RunLineageRecord,
    RunLineageStore,
    build_lineage_record,
)
from yolo_agent.core.resource_scheduler import (
    GPUResource,
    ResourceDecision,
    ResourceScheduler,
    ResourceSchedulerConfig,
    ResourceSnapshot,
    current_resource_snapshot,
)
from yolo_agent.core.stage_contract import (
    ArtifactContract,
    LoopStageContracts,
    RetryPolicy,
    StageContract,
    StageContractCheck,
)

__all__ = [
    "AgentConfig",
    "ARTIFACT_MANIFEST_SCHEMA_VERSION",
    "ArtifactManifest",
    "ArtifactManifestEntry",
    "ArtifactType",
    "BenchmarkImporter",
    "BenchmarkImportResult",
    "COCO_BASELINE_REQUIRED_ARTIFACTS",
    "COCO_BASELINE_REQUIRED_METRICS",
    "CocoBaselineEvidenceContract",
    "CocoBaselineEvidenceResult",
    "CocoBaselineNodeStatus",
    "CocoErrorFactSelector",
    "CocoErrorFocus",
    "CocoErrorSelectionResult",
    "CommandSpec",
    "CommandType",
    "DatasetProfile",
    "DatasetDiff",
    "DatasetFileRecord",
    "DatasetPromotionPolicy",
    "DatasetPromotionPolicyConfig",
    "DatasetPromotionResult",
    "DatasetSample",
    "DatasetSplitPlan",
    "DatasetSplitPlanner",
    "DeploymentConstraints",
    "DatasetSpec",
    "DatasetVersionManifest",
    "DatasetVersionStore",
    "DecisionLedger",
    "DecisionLedgerRecord",
    "DecisionReplaySnapshot",
    "DECISION_LEDGER_SCHEMA_VERSION",
    "KNOWN_LOOP_STAGES",
    "DeploymentSpec",
    "DuplicateGroup",
    "DryRunExecutor",
    "Evidence",
    "EvidenceStatusSummary",
    "EvidenceContract",
    "EventLog",
    "EventLogEntry",
    "GPUResource",
    "EvidenceGate",
    "EvidenceGateResult",
    "EvidenceIndex",
    "EvidenceRequirement",
    "EvidenceSelection",
    "EvidenceSelector",
    "EvidenceStore",
    "MATCHED_BASELINE_SCHEMA_VERSION",
    "MatchedBaselineControl",
    "MatchedBaselineKey",
    "PairedMetricDelta",
    "PairedBootstrapCI",
    "PairedErrorFactDelta",
    "PairedExperimentResult",
    "build_paired_experiment_result",
    "build_match_key",
    "match_baseline_control",
    "paired_metric_delta",
    "EvidenceStatus",
    "ErrorFact",
    "ErrorFactIndex",
    "ErrorFactQuery",
    "ErrorFactStore",
    "ErrorFactType",
    "ExecutionResult",
    "ExecutionStatus",
    "ExecutionQueue",
    "ExecutionQueueItem",
    "ExecutionQueueStore",
    "ROUND_EXECUTION_PLAN_SCHEMA_VERSION",
    "RoundAblationNode",
    "RoundAssignment",
    "RoundExecutionPlan",
    "RoundStageSpec",
    "SurvivorDecision",
    "build_round_execution_plan",
    "ExperimentExecutor",
    "ExperimentNode",
    "ExperimentPlan",
    "ExperimentStatus",
    "AnnotationRules",
    "ArtifactContract",
    "AutoOptimizationStatus",
    "LabelQualityIssue",
    "LabelQualityReport",
    "LeakagePair",
    "LINEAGE_SCHEMA_VERSION",
    "LoopRunStatus",
    "LoopStageState",
    "LoopStageContracts",
    "LoopState",
    "LLMDecisionConfig",
    "MetricPriority",
    "METRIC_SCHEMA_VERSION",
    "MetricEvidence",
    "MetricEvidenceQuery",
    "MetricValue",
    "NO_EVIDENCE_WARNING",
    "PredictionBox",
    "PolicyVariableClassification",
    "PromptContract",
    "QueueItemStatus",
    "QueueStatus",
    "PromotionDecision",
    "ResourceDecision",
    "ResourceRequirements",
    "ResourceScheduler",
    "ResourceSchedulerConfig",
    "ResourceSnapshot",
    "RunContext",
    "RunLineageGraph",
    "RunLineageRecord",
    "RunLineageStore",
    "RetryPolicy",
    "ReviewedLabelSample",
    "ReviewedLabels",
    "ReviewStatus",
    "ScenarioHint",
    "SelectionMode",
    "ShellExecutor",
    "SplitAssignment",
    "StageContract",
    "StageContractCheck",
    "TaskSpec",
    "TrainingHeartbeat",
    "UltralyticsExecutor",
    "UltralyticsTrainExecutor",
    "YoloBox",
    "analyze_label_quality",
    "build_lineage_record",
    "build_error_facts_from_coco_error_report",
    "build_error_facts_from_coco_metrics",
    "build_replay_snapshot",
    "coerce_metric_value",
    "coco_metric_aliases",
    "current_resource_snapshot",
    "load_loop_status",
    "load_llm_decision_config",
    "read_metric_mapping",
    "read_metric_records",
    "load_reviewed_labels",
    "queue_status_from_execution_status",
    "classify_policy_variables",
    "sha256_directory",
    "sha256_file",
    "sha256_model",
    "sha256_path",
    "render_loop_status",
    "select_coco_error_facts",
    "select_metric_evidence",
]
