"""Ultralytics adapter scaffold."""

from yolo_agent.adapters.ultralytics.adapter import UltralyticsAdapter
from yolo_agent.adapters.ultralytics.yaml_generator import (
    UltralyticsYamlGenerator,
    YamlGenerationResult,
    generate_ultralytics_yaml,
)
from yolo_agent.adapters.ultralytics.loss_adapter import (
    BBoxLossAdapter,
    CIoULossAdapter,
    LossRegistry,
    MPDIoULossAdapter,
    NWDLossAdapter,
    WIoULossAdapter,
    default_loss_registry,
)
from yolo_agent.adapters.ultralytics.training import (
    TrainingBudgetProfile,
    TrainingBudgetProfileName,
    UltralyticsRunImporter,
    UltralyticsTrainingConfig,
    Yolo26CocoGoal,
    command_from_training_config,
    default_training_budget_profiles,
    parse_results_csv,
    parse_ultralytics_run,
)
from yolo_agent.adapters.ultralytics.runtime_profiler import (
    RuntimeProfile,
    RuntimeProfiler,
    RuntimeSampler,
    RuntimeSample,
    parse_runtime_line_metrics,
    sample_nvidia_smi,
    write_runtime_profile,
)
from yolo_agent.adapters.ultralytics.batch_tuner import (
    BatchTuner,
    BatchTuningConfig,
    BatchTuningResult,
    BatchTrialResult,
    apply_selected_batch,
    build_batch_trial_command,
    should_tune_batch,
)
from yolo_agent.adapters.ultralytics.data_cache_policy import (
    DataCacheDecision,
    DataCachePolicy,
    DataCachePolicyConfig,
    MemorySnapshot,
    apply_cache_decision,
    current_memory_snapshot,
    detect_storage_kind,
    estimate_yolo_image_bytes,
)
from yolo_agent.adapters.ultralytics.fast_baseline_gate import (
    FastBaselineGate,
    FastBaselineGateConfig,
    FastBaselineGateResult,
)

__all__ = [
    "BatchTuner",
    "BatchTuningConfig",
    "BatchTuningResult",
    "BatchTrialResult",
    "BBoxLossAdapter",
    "CIoULossAdapter",
    "DataCacheDecision",
    "DataCachePolicy",
    "DataCachePolicyConfig",
    "FastBaselineGate",
    "FastBaselineGateConfig",
    "FastBaselineGateResult",
    "LossRegistry",
    "MPDIoULossAdapter",
    "MemorySnapshot",
    "NWDLossAdapter",
    "TrainingBudgetProfile",
    "TrainingBudgetProfileName",
    "RuntimeProfile",
    "RuntimeProfiler",
    "RuntimeSampler",
    "RuntimeSample",
    "UltralyticsAdapter",
    "UltralyticsRunImporter",
    "UltralyticsTrainingConfig",
    "UltralyticsYamlGenerator",
    "WIoULossAdapter",
    "YamlGenerationResult",
    "Yolo26CocoGoal",
    "apply_cache_decision",
    "apply_selected_batch",
    "build_batch_trial_command",
    "command_from_training_config",
    "current_memory_snapshot",
    "default_loss_registry",
    "default_training_budget_profiles",
    "detect_storage_kind",
    "estimate_yolo_image_bytes",
    "generate_ultralytics_yaml",
    "parse_results_csv",
    "parse_runtime_line_metrics",
    "parse_ultralytics_run",
    "sample_nvidia_smi",
    "should_tune_batch",
    "write_runtime_profile",
]
