"""Safe Ultralytics model YAML draft generation."""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml
from pydantic import BaseModel, Field

from yolo_agent.agents.candidate_generator import CandidateConfig


class YamlGenerationResult(BaseModel):
    """Result of generating an Ultralytics YAML draft."""

    output_path: Path
    dry_run: bool = False
    changes: list[str] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)


class UltralyticsYamlGenerator:
    """Generate conservative Ultralytics model YAML drafts from candidates."""

    def generate(
        self,
        candidate: CandidateConfig,
        base_template: Path | str,
        output_dir: Path | str = "generated_models",
        nc: int | None = None,
        scales: dict[str, Any] | None = None,
        dry_run: bool = False,
    ) -> YamlGenerationResult:
        """Generate a model YAML draft for a candidate."""
        template_path = Path(base_template)
        output_path = Path(output_dir) / f"{candidate.candidate_id}.yaml"
        model_yaml = _load_yaml_mapping(template_path)
        changes: list[str] = [f"copy baseline template: {template_path} -> {output_path}"]
        warnings = _component_warnings(candidate)

        if nc is not None:
            model_yaml["nc"] = nc
            changes.append(f"set nc={nc}")

        if scales is not None:
            model_yaml["scales"] = scales
            changes.append("replace scales")
        elif candidate.scale:
            existing_scales = model_yaml.get("scales")
            if isinstance(existing_scales, dict) and candidate.scale in existing_scales:
                model_yaml["scales"] = {candidate.scale: existing_scales[candidate.scale]}
                changes.append(f"narrow scales to candidate scale={candidate.scale}")

        if dry_run:
            _print_dry_run(candidate, output_path, changes, warnings)
            return YamlGenerationResult(
                output_path=output_path,
                dry_run=True,
                changes=changes,
                warnings=warnings,
            )

        output_path.parent.mkdir(parents=True, exist_ok=True)
        with output_path.open("w", encoding="utf-8") as file:
            file.write(_metadata_comment(candidate, warnings))
            yaml.safe_dump(model_yaml, file, sort_keys=False)

        return YamlGenerationResult(
            output_path=output_path,
            changes=changes,
            warnings=warnings,
        )


def generate_ultralytics_yaml(
    candidate: CandidateConfig,
    base_template: Path | str,
    output_dir: Path | str = "generated_models",
    nc: int | None = None,
    scales: dict[str, Any] | None = None,
    dry_run: bool = False,
) -> YamlGenerationResult:
    """Convenience wrapper for generating one Ultralytics model YAML draft."""
    return UltralyticsYamlGenerator().generate(
        candidate=candidate,
        base_template=base_template,
        output_dir=output_dir,
        nc=nc,
        scales=scales,
        dry_run=dry_run,
    )


def _load_yaml_mapping(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as file:
        data = yaml.safe_load(file) or {}
    if not isinstance(data, dict):
        raise ValueError(f"Ultralytics base model YAML must contain a mapping: {path}")
    return data


def _component_warnings(candidate: CandidateConfig) -> list[str]:
    warnings: list[str] = []
    for component_id in candidate.components:
        if component_id == "head.p2_small_object":
            warnings.append(
                "TODO: head.p2_small_object requested; add P2 head manually after architecture review."
            )
        elif component_id.startswith("neck.fullpad") or component_id.startswith("neck.hyperace"):
            warnings.append(
                f"Compatibility warning: {component_id} requires a neck/channel-adapter draft review."
            )
        elif component_id.startswith("backbone.") or component_id.startswith("head.") or component_id.startswith("neck."):
            warnings.append(
                f"Unsupported structural component {component_id}; copied baseline YAML without topology changes."
            )
        elif component_id.startswith("loss.") or component_id.startswith("assigner."):
            warnings.append(
                f"{component_id} is a training/config component; model YAML topology was not changed."
            )
        else:
            warnings.append(
                f"Unsupported component {component_id}; copied baseline YAML without changes for it."
            )
    return warnings


def _metadata_comment(candidate: CandidateConfig, warnings: list[str]) -> str:
    lines = [
        "# Generated by yolo-agent UltralyticsYamlGenerator.",
        f"# candidate_id: {candidate.candidate_id}",
        f"# base_model: {candidate.base_model}",
        f"# scale: {candidate.scale}",
        f"# framework: {candidate.framework}",
        f"# risk: {candidate.risk}",
    ]
    if candidate.components:
        lines.append("# components:")
        lines.extend(f"#   - {component_id}" for component_id in candidate.components)
    if candidate.expected_effect:
        lines.append("# expected_effect:")
        lines.extend(f"#   - {effect}" for effect in candidate.expected_effect)
    if warnings:
        lines.append("# generator_warnings:")
        lines.extend(f"#   - {warning}" for warning in warnings)
    lines.append("")
    return "\n".join(lines)


def _print_dry_run(
    candidate: CandidateConfig,
    output_path: Path,
    changes: list[str],
    warnings: list[str],
) -> None:
    print(f"dry-run: would generate {output_path}")
    print(f"candidate_id={candidate.candidate_id}")
    for change in changes:
        print(f"change: {change}")
    for warning in warnings:
        print(f"warning: {warning}")

